Add CI/CD pipeline with linter and training jobs

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -1,1 +1,56 @@
+name: CI/CD Pipeline
 
+on:
+  push:
+    branches:
+      - main
+      - develop
+      - feature/**
+
+jobs:
+  linter:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Run Linter
+        run: |
+          echo "Running lint checks..."
+          echo "Lint Passed!"
+
+  train:
+    runs-on: ubuntu-latest
+    needs: linter
+
+    if: >
+      needs.linter.result == 'success' &&
+      github.ref == 'refs/heads/main' &&
+      contains(github.event.head_commit.message, '[run-train]')
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Run training
+        run: |
+          echo "Start Training..."
+          exit 1
+
+      - name: Save error logs
+        if: failure()
+        run: |
+          echo "Training failed!" > error_logs.txt
+
+      - name: Upload logs
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: error-logs
+          path: error_logs.txt
+
+      - name: Cleanup
+        if: always()
+        run: |
+          echo "Cleaning up temporary cloud volumes..."
